### ISSUE TITLE
Fields on `Expansions` aren't accessible

### ISSUE THREAD

**Issue by wingertge** [jpopesculian/twitter-v2-rs#1]
All fields on the `Expansions` struct are currently private. This makes it quite useless right now and makes it impossible to retrieve things like image URLs and usernames from the tweet API. They should be made public.

**Comment by jpopesculian** [comment]
Hi! You're absolutely right! Ill put out a fix tonight!

**Comment by jpopesculian** [comment]
Hi @wingertge newest release should fix your issues https://github.com/jpopesculian/twitter-v2-rs/commit/81204bc27e6e07d44d4cf7851bbd2d8b107a97a3
