### ISSUE TITLE
Deserialization for `Media` fails if the JSON has no `duration_ms` field

### ISSUE THREAD

**Issue by wingertge** [jpopesculian/twitter-v2-rs#2]
This is probably because of the custom deserializer on `duration` but I can't figure why it's behaving that way.

**Comment by jpopesculian** [comment]
Hi @wingertge newest release should fix your issues https://github.com/jpopesculian/twitter-v2-rs/commit/81204bc27e6e07d44d4cf7851bbd2d8b107a97a3
